### ISSUE TITLE
Cfdestination hardcoded compatibility

### ISSUE THREAD

**Issue by Magoli1** [ui5-community/ui5-ecosystem-showcase#185]
Hey everyone,

I am currently trying to get a scenario running, where the cfdestination middleware (and hence the sap approuter) is used as a proxy to access the real (sandbox) systems, to fetch data. To enable this, the approuter is able to pick up the default-env.json and default-services.json by default. This would allow developers to easily test the ui from their localhost with real backend data, in addition to using the mockserver.

The only thing that hinders me from getting that setup running is the fact that there is no option to configure the authenticationMethod from the ui5.yaml.

I could imagine a new config-option ``keepAuthenticationMethod`` which is defaulted to ``false`` to keep backward compatibility. Setting it to ``true`` would keep the authentication method from the ``xs-app.json``.

Another restriction that could hinder compatibility to a broader range of projects is the fact, that the middleware expects the destination section in the yaml. Not providing it (eg. in case you only have business services configured in the xs-app.json and no destination) results in an invalid value for the environment variable (``undefined``) and thus an error. This could also be resolved by defaulting it to ``{}``.

What do you think about these enhancements? I would be happy to create two seperate PRs for this.

Best Regards
Robert

**Comment by vobu** [comment]
even though i authored the original plugin, i never used it with authentication. but had a hunch that it should work as designed for local -> remote-cf auth scenarios. then @IObert said it doesn't: https://github.com/petermuessig/ui5-ecosystem-showcase/pull/163#issuecomment-607850560
so i'm pointing fingers his way 👉 😀 and hope he'll join in on the discussion

**Comment by Magoli1** [comment]
In the scenario where authentication should be disabled, this perfectly makes sense, as you do not want to load any default environment, you just wanna proxy to an URL.  I think thats what @IObert meant, and thats also what is achieved by hardcoding the setting👍 
But in the case you would like to have auth, then this also implies, that you have a default-env in some form supplied.

**Comment by IObert** [comment]
Hi,
Yes, the current state was a hotfix to allow the usage of destinations that don't require authentication. What you're describing is a valid scenario and it makes sense to add another config option to decide whether the authmethod should be overridden or not.

I also did a short POC to read the env var and check if an xsuaa service instance is bound and decide based on this information whether the authmethod should be overridden. My initial impression was that it doesn't make sense to use authentication without an xsuaa binding.
It was possible to check for the variable and the redirect to the logon page worked as well. Unfortunately, the redirect from the IdP back to the approuter did not work as expected, which is why I discarded the POC.

If you have an idea on how to make this work, it would be great if you are willing to open a PR.

PS: I had a similar discussion about this last week with Holger Schäfer from the OpenUI5 workspace. I'll ping him to see whether the wants to join this discussion as well.

**Comment by Magoli1** [comment]
Hey @IObert,

I agree, that it is not the standard way to have authentication without an xsuaa binding and I would also propose to only go the standard way provided by approuter, which is letting it pick up default-env and/or default-services.json files.
I just checked back with a colleague about the redirect back to the app from xsuaa after login. In his case, he is starting the approuter manually from another folder, and thus needs to manually change paths from the xs-app.json and the ui5 app, which I believe would not be needed in our case.

Other than that, everything worked right out of the box, without any custom code and only supplying the default*.json files. 

Maybe we could have a look at the POC code, if you can still find it? 👍 

Best Regards
Robert

**Comment by hschaefer123** [comment]
Hi,
concerning @IObert 
>Unfortunately, the redirect from the IdP back to the approuter did not work as expected, which is why I discarded the POC.
I found: https://developers.sap.com/tutorials/sac-embed-story.html
where there manually handle the callback redirect.

My POC also stopped at this point, but that is a solution to solve it.

My szenario is the same like the one from Robert.
I even want to test/develop lokal appRouter while beeing connected to the real backend systems supporting html5apprepo, destination and connectivity service and odata onprem behind connectivity.

Inside my ui5 app, i would like to use Cfdestination middleware just to proxy cf destination for all the services an thought that the approuter will handle all saml stuff and services proxiing. My idea is only changing the originally used xs-app.json and pointing out the current html5app repo uri's to the local file system (while even use the routes to html5apprepo to be able to access the used custom theme from remote. 

My current shop stopper was also the callback, which was not handled by the approuter out-of-the-box, but if i have some time, i will give it a retry with the approach in the blog.

Let me now, if you have been successfully earlier ;-)

Regards Holger

**Comment by vobu** [comment]
we are/were on this with #528 - halfway through, i'd say.
what works: local runtime, remote authentication against a BTP (IdP) instance.
what doesn't work and probably never will: call _remote BTP destinations_ from a local runtime. Reason for this is that the proxy runtime in BTP doesn't allow connections from public networks, not even for an authenticated session. That's why there's e.g. https://github.com/jowavp/sap-cf-proxy that requires an SSH tunnel `local`<->`BTP` for subsequent http calls.
