### ISSUE TITLE
[ui5-task-i18ncheck] works fine; will unused i18n properties also be identified?

### ISSUE THREAD

**Issue by jvanattedev** [ui5-community/ui5-ecosystem-showcase#524]
As far as I can see, this task works as expected: i18n properties used in XML Views but not present in i18n files are identified. 

I was wondering whether you could also identify properties in i18n files, which are unused in the xml views?

**Comment by petermuessig** [comment]
Hi @jvanattedev ,

sorry for the late reply - I missed you issue. Should be also possible - you would just need to do the check vice-versa. @fatihpense did you think about this direction as well? Anyways, @jvanattedev - this repo is open for contributions, if you want you can contribute this feature... 😄 

Best regards,
Peter

**Comment by petermuessig** [comment]
I think this feature would require additional functionality to understand also the JavaScript or TypeScript source code - since we need to find the places there as well in which texts are being used. And those texts could eventually be concatenated which would make the determination more complex. So, I think this is out of scope to implement it this way round...
