### ISSUE TITLE
What happens with assets such as css, img, audio, video, etc

### ISSUE THREAD

**Issue by mauriciolauffer** [ui5-community/ui5-ecosystem-showcase#590]
It isn't a bug, it's to start a discussion...

What would happen when a pkg has assets which may are direct accessed by js (css, img, audio, video, etc)? Or, has plugins in subfolders which are not npm pkgs? For instance, [amchats](https://www.amcharts.com/docs/v4/concepts/themes/)

What if the pkg is already built and minified in a dist folder. For instance, [Ajv](https://www.npmjs.com/package/ajv)

Wouldn't that be better if `ui5-tooling-modules` just copied content from npm pkg rather than building/traversing the code with rollup? It could follow package.json [main](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main) or 
[browser](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser) or from the root, and copy the folder content.

**Comment by petermuessig** [comment]
I had a similar discussion already after showing my solution with the inclusion of CSS. By resolving it via `sap.ui.require.toUrl` is is marked as to be included: 
https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-app-module/Chart.js#L48

But in general, we should rather think of a concept to just copy all assets into the dist of the application with the task. For the middleware, there is no issue as when you address the assets they can be just resolved and served. But for the build we need to somehow either mark the dependencies (my idea of implicit marking above) or just add some config which explains what to copy. Maybe it is in general the easiest one to just copy all assets of the required modules (except of JS - since we somehow require it) when configured in the plugin.

WDYT?
