### ISSUE TITLE
The tool does not work for  lib cmis .

### ISSUE THREAD

**Issue by horsemanjackyliu** [ui5-community/ui5-ecosystem-showcase#659]
**Describe the bug**
The tool does not work for  lib [cmis](https://www.npmjs.com/package/cmis) .

**To Reproduce**
1. git clone from https://github.com/horsemanjackyliu/cmissearch.git
2. run command :  cd  com.sap.cmissearch4
3. run command :  npm run build:mta
4. run command :  npm run start
5. open browser with address https://localhost:8080/indext.html
6. open browser developer tool, you will find the error : failed to execute module factory for ''cmis.js'': exports is not defined

**Expected behavior**
No error shows . The button "click me" shows in the browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC IOS
 - Browser  chrome
 - Version 107.0.5304.121

![image](https://user-images.githubusercontent.com/74337345/208061082-c16a8bfb-fb95-4679-b13e-6ad632f2a9f0.png)

![image](https://user-images.githubusercontent.com/74337345/208061282-a3d46827-f783-4657-b3fb-363a2e9cd102.png)

**Comment by petermuessig** [comment]
Hi @horsemanjackyliu ,

sorry for my late reply, I created a small example for the usage of the cmis package within a UI5 application either by using `ui5-tooling-modules` or shimming. You can download the example from here: [com.myorg.myapp.zip](https://github.com/ui5-community/ui5-ecosystem-showcase/files/10276880/com.myorg.myapp.zip)

After downloading and extracting the zip, just run `npm install` and `npm start` to see the demo application. If you have the debugger open, the browser will stop in the `Main.controller.js` which demonstrates the two different ways of importing the cmis package, either via ' ui5-tooling-modules` or via shimming. I added some more description in there...

The solution is to use the cmis.bundle.js instead of the cmis.js - but I'll check whether the `ui5-tooling-modules` can be improved here. AFAICS, the usage of `cmis` directly is only for the Node scenario and in the browser the `cmis.bundle.js` should be used as described here: https://www.npmjs.com/package/cmis

HTH

**Comment by petermuessig** [comment]
Hi @horsemanjackyliu ,

with the recent changes of the `ui5-tooling-modules` extension it is now also possible to use `cmis` directly as dependency. By upgrading to the latest rollup and rollup plugins versions, the bundling has been improved under the hood. I also adopted the `ui5-app` sample project to include `cmis` and to verify it: PR #670. 

I'll close the issue now. The workaround is an option and with the release of `ui5-tooling-modules@0.7.2` `cmis` now works without workaround. 

THX for reporting! Best regards
