### ISSUE TITLE
[cds-plugin-ui5] Does not apply UI5 Workspaces config

### ISSUE THREAD

**Issue by BenReim** [ui5-community/ui5-ecosystem-showcase#830]
**Describe the bug**
If the ui5 project contains a `ui5-workspace.yaml` with a default workspace config, it should be automatically applied. 

**Expected behavior**
The workspace config should be applied during the servers bootstrap, e.g.: 
```shell
info graph:providers:NodePackageDependencies Resolved module ui5-reuse-lib via default workspace to version 1.0.0
```

**Comment by matz3** [comment]
This is probably because of the fact that the graph APIs do not use "default" as a default for the workspaceName.
It hasn't been designed in that way but was rather missed and we decided to not change the behaviour once we noticed that  to avoid breaking changes.
We'll fix that in v4 to use "default" unless `null` is passed which would then suppress the default workspace usage.

https://github.com/ui5-community/ui5-ecosystem-showcase/blob/71fa6b602a0b18969d2ebe8b90d3f47f448ad9d4/packages/cds-plugin-ui5/lib/applyUI5Middleware.js#L27
This line should be changed to use a default "default" in case the environment variable is not defined.
